"""Shared helpers for correctness tests."""

from __future__ import annotations

from functools import lru_cache
import itertools
import random
from typing import Dict, List, Sequence, Tuple

from burnside_sampler.pure_python import (
    Matrix,
    Partition,
    Vector,
    identity_matrix,
    in_span,
    mat_inv,
    mat_mul,
    mat_vec,
    matrix_from_columns,
    normalize_partition,
    rank,
    row_reduce,
)


def jordan_block_matrix(partition: Sequence[int], q: int) -> Matrix:
    """Jordan matrix with ones on the diagonal and superdiagonal."""
    normalized = normalize_partition(partition)
    rows = [list(row) for row in identity_matrix(sum(normalized))]
    offset = 0
    for part in normalized:
        for index in range(part - 1):
            rows[offset + index][offset + index + 1] = 1 % q
        offset += part
    return tuple(tuple(entry % q for entry in row) for row in rows)


def rref_signature(rows: Sequence[Sequence[int]], q: int) -> Tuple[Tuple[int, ...], ...]:
    """Canonical signature of the row span generated by ``rows``."""
    reduced, pivots = row_reduce(rows, q)
    return tuple(tuple(row) for row in reduced[: len(pivots)])


def flag_signature(flag: Sequence[Sequence[int]], q: int) -> Tuple[Tuple[Tuple[int, ...], ...], ...]:
    """Canonical signature of a complete flag."""
    return tuple(rref_signature(flag[:index], q) for index in range(1, len(flag) + 1))


@lru_cache(maxsize=None)
def all_complete_flags(n: int, q: int) -> Tuple[Tuple[Vector, ...], ...]:
    """Enumerate all complete flags in ``F_q^n``."""
    nonzero_vectors = [
        tuple(vector)
        for vector in itertools.product(range(q), repeat=n)
        if any(vector)
    ]
    current: Dict[Tuple[Tuple[Tuple[int, ...], ...], ...], Tuple[Vector, ...]] = {
        tuple(): tuple()
    }

    for _ in range(n):
        next_flags: Dict[Tuple[Tuple[Tuple[int, ...], ...], ...], Tuple[Vector, ...]] = {}
        for signature, flag in current.items():
            local_extensions: Dict[Tuple[Tuple[int, ...], ...], Tuple[Vector, ...]] = {}
            for vector in nonzero_vectors:
                candidate = flag + (vector,)
                if rank(candidate, q) != len(candidate):
                    continue
                top_signature = rref_signature(candidate, q)
                local_extensions.setdefault(top_signature, candidate)
            for top_signature, candidate in local_extensions.items():
                next_flags[signature + (top_signature,)] = candidate
        current = next_flags

    return tuple(current.values())


def is_stable_complete_flag(A: Matrix, flag: Sequence[Sequence[int]], q: int) -> bool:
    """Check that a flag is complete and each step is ``A``-stable."""
    for index in range(1, len(flag) + 1):
        basis = list(flag[:index])
        if rank(basis, q) != index:
            return False
        for vector in basis:
            if not in_span(mat_vec(A, tuple(vector), q), basis, q):
                return False
    return True


def random_invertible_matrix(n: int, q: int, rng: random.Random) -> Matrix:
    """Random invertible matrix over ``F_q``."""
    while True:
        rows = [
            tuple(rng.randrange(q) for _ in range(n))
            for _ in range(n)
        ]
        if rank(rows, q) == n:
            return tuple(rows)


def random_general_unipotent_matrix(partition: Partition, q: int, rng: random.Random) -> Matrix:
    """Random conjugate of a Jordan matrix with the given partition."""
    J = jordan_block_matrix(partition, q)
    P = random_invertible_matrix(sum(partition), q, rng)
    Pinv = mat_inv(P, q)
    return mat_mul(mat_mul(P, J, q), Pinv, q)


def quotient_action_matches(A: Matrix, quotient: Matrix, basis: Sequence[Sequence[int]], q: int) -> bool:
    """Check that ``quotient`` is the induced action on ``V / <basis[0]>``."""
    kernel = [tuple(basis[0])]
    quotient_basis = [tuple(vector) for vector in basis[1:]]
    for column, basis_vector in enumerate(quotient_basis):
        lhs = mat_vec(A, basis_vector, q)
        rhs = [0] * len(basis_vector)
        for coeff, vector in zip((row[column] for row in quotient), quotient_basis):
            for index, entry in enumerate(vector):
                rhs[index] = (rhs[index] + coeff * entry) % q
        difference = tuple((left - right) % q for left, right in zip(lhs, rhs))
        if not in_span(difference, kernel, q):
            return False
    return True
